name = "cake_gmysql"
version = "1.0.0"
description = "ğŸ‚Cake ğŸ¦­MariaDB and ğŸ¬MySQL adapters which which pass PreparedStatements to the gmysql library for execution written in Gleam."
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-cake-gmysql" }
# links = [{ title = "Website", href = "https://gleam.run" }]

gleam = ">= 1.4.0 and < 2.0.0"

[documentation]
pages = [
  { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
]

[dependencies]
cake = ">= 2.0.0 and < 3.0.0"
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
gmysql = ">= 1.4.0 and < 2.0.0"
